library("corrplot")
library(RColorBrewer)
pooled<-read.csv("cor_pooled.csv")
single<-read.csv("cor_single.csv")
pdf("Corelation_single_pooled.pdf")
co<-cor(single,pooled,method = "pearson")
corrplot(co, type = "lower", order = "hclust",col = brewer.pal(n = 8, name = "PuOr"))
corrplot(co,method="circle")
corrplot(co,method="number")
corrplot.mixed(co, lower.col = "black", number.cex = .7)
corrplot(co, method="color")
corrplot(co, method="pie")
corrplot(co, type="lower")
corrplot(co, type="upper", order="hclust", tl.col="black", tl.srt=45)
corrplot(co, type="upper", order="hclust",col=brewer.pal(n=11, name="PuOr"))
corrplot(co, type="upper", order="hclust",col=brewer.pal(n=11, name="RdYlBu"))
corrplot(co, type="upper", order="hclust", col=brewer.pal(n=11, name="RdBu"))
corrplot(co, type="upper", order="hclust", col=c("black", "white"),bg="lightblue")
col<- colorRampPalette(c("red", "white", "blue"))(20)
corrplot(co, type="upper", order="hclust", col=col)
corrplot(co, type="upper", order="hclust")
dev.off()
